/**
* these code generated by opcode_gen subproject!
* do not try to modify it!!!
* @see		jmp0.abc.opcode_gen
* support bytecode version: 13.0.1.0
*
* @Author: jmp0
* @Email: jmp0@qq.com
*/
package jmp0.abc.disasm.types;

import lombok.Getter;

@Getter
public enum PandaOPCodeFormat {
	IMM8_IMM8_V8(3),
	PREF_ID32(4),
	PREF_ID32_IMM8(5),
	PREF_NONE(0),
	V8_V8_V8_V8(4),
	ID16(2),
	IMM16(2),
	IMM8_ID16_IMM8(4),
	PREF_IMM16(2),
	IMM8_V8_V8_V8_V8(5),
	V8_V8_V8(3),
	V8(1),
	IMM8(1),
	IMM8_V8_IMM16(4),
	PREF_IMM16_V8_V8(4),
	PREF_IMM16_ID16(4),
	PREF_IMM16_IMM16_V8(5),
	PREF_IMM8_V8_V8(3),
	IMM16_IMM8_V8(4),
	IMM8_IMM16_IMM16(5),
	PREF_ID32_V8(5),
	V8_V8(2),
	PREF_ID16_IMM16_IMM16_V8_V8(8),
	PREF_IMM4_IMM4_V8(2),
	PREF_IMM8_IMM8_V8(3),
	IMM4_IMM4(1),
	IMM8_ID16(3),
	V8_IMM8(2),
	IMM8_V8_V8(3),
	V16_V16(4),
	IMM8_IMM8(2),
	NONE(0),
	PREF_IMM16_V8(3),
	IMM16_ID16_V8(5),
	IMM16_ID16_ID16_IMM16_V8(9),
	V8_IMM16(3),
	PREF_IMM32(4),
	PREF_IMM8(1),
	PREF_V8_V8_V8_V8(4),
	IMM16_V8_V8(4),
	PREF_V8(1),
	IMM8_ID16_V8(4),
	PREF_ID16(2),
	PREF_IMM8_IMM16_IMM16_V8(6),
	IMM32(4),
	IMM16_ID16_IMM8(5),
	PREF_IMM16_ID16_ID16_IMM16_V8(9),
	PREF_IMM8_IMM8(2),
	PREF_V8_IMM32(5),
	IMM8_IMM16_IMM16_V8(6),
	IMM16_V8(3),
	PREF_IMM4_IMM4(1),
	V4_V4(1),
	IMM8_V8_V8_V8(4),
	IMM8_ID16_ID16_IMM16_V8(8),
	PREF_V8_V8(2),
	IMM8_IMM16(3),
	IMM16_IMM16(4),
	PREF_IMM8_IMM32_V8(6),
	PREF_V8_V8_V8(3),
	IMM16_ID16(4),
	IMM64(8),
	PREF_IMM8_V8(2),
	IMM16_V8_IMM16(5),
	IMM8_V8(2),
	PREF_IMM16_IMM16(4);
    private final int paramSize;
    PandaOPCodeFormat(int paramSize){
        this.paramSize = paramSize;
    }
}
