/**
* these code generated by opcode_gen subproject!
* do not try to modify it!!!
* @see		jmp0.abc.opcode_gen
* support bytecode version: 13.0.1.0
*
* @Author: jmp0
* @Email: jmp0@qq.com
*/
package jmp0.abc.disasm.types;

import lombok.Getter;

@Getter
public enum PandaOPCodeFlag {
	TYPE_ID(0x1),
	METHOD_ID(0x2),
	STRING_ID(0x4),
	LITERALARRAY_ID(0x8),
	FIELD_ID(0x10),
	CALL(0x20),
	CALL_VIRT(0x40),
	RETURN(0x80),
	SUSPEND(0x100),
	JUMP(0x200),
	CONDITIONAL(0x400),
	FLOAT(0x800),
	DYNAMIC(0x1000),
	MAYBE_DYNAMIC(0x2000),
	LANGUAGE_TYPE(0x4000),
	INITIALIZE_TYPE(0x8000),
	IC_SLOT(0x10000),
	JIT_IC_SLOT(0x20000),
	ONE_SLOT(0x40000),
	TWO_SLOT(0x80000),
	EIGHT_BIT_IC(0x100000),
	SIXTEEN_BIT_IC(0x200000),
	EIGHT_SIXTEEN_BIT_IC(0x400000),
	CONDITIONAL_THROW(0x800000),
	RANGE_0(0x1000000),
	RANGE_1(0x2000000),
	NO_SIDE_EFFECT(0x4000000),
	ACC_NONE(0x8000000),
	ACC_READ(0x10000000),
	ACC_WRITE(0x20000000);
    private final int value;
    PandaOPCodeFlag(int value){
        this.value = value;
    }
}
